//! Bounded, structured operational diagnostics. No message body, user name,
//! credential, URL, file path or provider response is accepted by this API.

use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::Serialize;

const MAX_LOG_BYTES: u64 = 1024 * 1024;
const ROTATED_FILES: usize = 4;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DiagnosticCode {
    AppStarted,
    AppStopped,
    UiActivity,
    UiMemoryTarget,
    RoomConnecting,
    RoomConnected,
    RoomReconnecting,
    RoomStopped,
    RoomFailed,
    EventDropped,
    PlanFailed,
    QueueSkipped,
    QueueCleared,
    QueueStopped,
    PlaybackFailed,
    AudioDisconnected,
    LegacyImportApplied,
    LegacyImportFailed,
}

#[derive(Serialize)]
struct Record {
    at_unix_ms: u128,
    code: DiagnosticCode,
    /// Only a numeric count or identifier generated by this app. No free text.
    number: Option<u64>,
}

pub struct DiagnosticLog {
    directory: PathBuf,
    file: Option<File>,
    bytes: u64,
}

impl DiagnosticLog {
    pub fn open(data_dir: &Path) -> io::Result<Self> {
        fs::create_dir_all(data_dir)?;
        let root = data_dir.canonicalize()?;
        let directory = data_dir.join("logs");
        if !entry_exists(&directory)? {
            fs::create_dir(&directory)?;
        }
        checked_local_entry(&directory, &root, true)?;
        let file_path = directory.join("current.jsonl");
        if entry_exists(&file_path)? {
            checked_local_entry(&file_path, &directory.canonicalize()?, false)?;
        }
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&file_path)?;
        let bytes = file.metadata()?.len();
        Ok(Self {
            directory,
            file: Some(file),
            bytes,
        })
    }

    pub fn directory(&self) -> &Path {
        &self.directory
    }

    pub fn record(&mut self, code: DiagnosticCode, number: Option<u64>) -> io::Result<()> {
        let at_unix_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis();
        let mut line = serde_json::to_vec(&Record {
            at_unix_ms,
            code,
            number,
        })
        .map_err(io::Error::other)?;
        line.push(b'\n');
        if self.bytes.saturating_add(line.len() as u64) > MAX_LOG_BYTES {
            self.rotate()?;
        }
        let file = self
            .file
            .as_mut()
            .ok_or_else(|| io::Error::other("日志文件未打开"))?;
        file.write_all(&line)?;
        file.flush()?;
        self.bytes += line.len() as u64;
        Ok(())
    }

    fn rotate(&mut self) -> io::Result<()> {
        let parent = self.directory.canonicalize()?;
        for name in [
            "current.jsonl",
            "previous-1.jsonl",
            "previous-2.jsonl",
            "previous-3.jsonl",
            "previous-4.jsonl",
        ] {
            let path = self.directory.join(name);
            if entry_exists(&path)? {
                checked_local_entry(&path, &parent, false)?;
            }
        }
        if let Some(mut file) = self.file.take() {
            file.flush()?;
        }
        for index in (2..=ROTATED_FILES).rev() {
            let previous = self.directory.join(format!("previous-{}.jsonl", index - 1));
            let destination = self.directory.join(format!("previous-{index}.jsonl"));
            if entry_exists(&previous)? {
                if entry_exists(&destination)? {
                    fs::remove_file(&destination)?;
                }
                fs::rename(previous, destination)?;
            }
        }
        let current = self.directory.join("current.jsonl");
        let first = self.directory.join("previous-1.jsonl");
        if entry_exists(&first)? {
            fs::remove_file(&first)?;
        }
        fs::rename(&current, &first)?;
        self.file = Some(OpenOptions::new().create(true).append(true).open(current)?);
        self.bytes = 0;
        Ok(())
    }
}

static GLOBAL: OnceLock<Mutex<DiagnosticLog>> = OnceLock::new();

/// Once per desktop process, after resolving `--data-dir`.
pub fn init(data_dir: &Path) -> io::Result<()> {
    if GLOBAL.get().is_some() {
        return Ok(());
    }
    let log = DiagnosticLog::open(data_dir)?;
    let _ = GLOBAL.set(Mutex::new(log));
    Ok(())
}

/// Recording must not delay or fail the audio callback. Call this only from
/// control tasks; it never runs on the CPAL realtime thread.
pub fn record(code: DiagnosticCode, number: Option<u64>) {
    if let Some(log) = GLOBAL.get()
        && let Ok(mut log) = log.lock()
    {
        let _ = log.record(code, number);
    }
}

/// Clear only this application's fixed diagnostic filenames. The caller has
/// already stopped all activities. A log belonging to another data directory
/// is left alone (important for isolated tests and explicit --data-dir use).
pub fn clear(data_dir: &Path) -> io::Result<()> {
    let root = data_dir.canonicalize()?;
    let directory = data_dir.join("logs");
    if !entry_exists(&directory)? {
        return Ok(());
    }
    checked_local_entry(&directory, &root, true)?;
    let names = [
        "current.jsonl",
        "previous-1.jsonl",
        "previous-2.jsonl",
        "previous-3.jsonl",
        "previous-4.jsonl",
    ];
    for name in names {
        let path = directory.join(name);
        if entry_exists(&path)? {
            checked_local_entry(&path, &directory.canonicalize()?, false)?;
        }
    }
    let mut global = GLOBAL
        .get()
        .map(|value| value.lock().map_err(|_| io::Error::other("日志锁不可用")))
        .transpose()?;
    let active = global
        .as_ref()
        .is_some_and(|log| log.directory.canonicalize().ok() == directory.canonicalize().ok());
    if active && let Some(log) = global.as_mut() {
        log.file.take();
    }
    let cleared = (|| {
        for name in names {
            let path = directory.join(name);
            if entry_exists(&path)? {
                fs::remove_file(path)?;
            }
        }
        Ok(())
    })();
    if active && let Some(log) = global.as_mut() {
        // Reopen even after a partial filesystem failure so later diagnostics
        // are usable; the caller still receives the original clear error.
        **log = DiagnosticLog::open(data_dir)?;
    }
    cleared
}

fn entry_exists(path: &Path) -> io::Result<bool> {
    match fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error),
    }
}

fn checked_local_entry(path: &Path, parent: &Path, directory: bool) -> io::Result<()> {
    let metadata = fs::symlink_metadata(path)?;
    let mut redirected = metadata.file_type().is_symlink();
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        redirected |= metadata.file_attributes() & 0x400 != 0;
    }
    if redirected || metadata.is_dir() != directory || path.canonicalize()?.parent() != Some(parent)
    {
        return Err(io::Error::other("日志路径不属于当前应用的数据目录"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(any(unix, windows))]
    #[test]
    fn redirected_log_file_is_rejected_before_open_or_clear() {
        let temp = tempfile::tempdir().unwrap();
        let data = temp.path().join("data");
        let directory = data.join("logs");
        fs::create_dir_all(&directory).unwrap();
        let outside = temp.path().join("outside.txt");
        fs::write(&outside, b"keep").unwrap();
        let link = directory.join("current.jsonl");
        #[cfg(unix)]
        let linked = std::os::unix::fs::symlink(&outside, &link);
        #[cfg(windows)]
        let linked = std::os::windows::fs::symlink_file(&outside, &link);
        if let Err(error) = linked {
            if error.kind() == io::ErrorKind::PermissionDenied {
                return; // Windows symlink creation may require Developer Mode.
            }
            panic!("failed to create test symlink: {error}");
        }
        assert!(DiagnosticLog::open(&data).is_err());
        assert!(clear(&data).is_err());
        assert_eq!(fs::read(&outside).unwrap(), b"keep");
    }

    #[test]
    fn reset_clears_only_fixed_diagnostic_files() {
        let temp = tempfile::tempdir().unwrap();
        let mut log = DiagnosticLog::open(temp.path()).unwrap();
        log.record(DiagnosticCode::AppStarted, None).unwrap();
        drop(log);
        let directory = temp.path().join("logs");
        fs::write(directory.join("previous-1.jsonl"), b"old log").unwrap();
        fs::write(directory.join("user-notes.jsonl"), b"keep").unwrap();
        clear(temp.path()).unwrap();
        assert!(!directory.join("current.jsonl").exists());
        assert!(!directory.join("previous-1.jsonl").exists());
        assert_eq!(
            fs::read(directory.join("user-notes.jsonl")).unwrap(),
            b"keep"
        );
        DiagnosticLog::open(temp.path())
            .unwrap()
            .record(DiagnosticCode::AppStarted, None)
            .unwrap();
    }

    #[test]
    fn rotation_is_bounded_and_only_uses_fixed_fields() {
        let temp = tempfile::tempdir().unwrap();
        let mut log = DiagnosticLog::open(temp.path()).unwrap();
        for number in 0..10 {
            log.bytes = MAX_LOG_BYTES;
            log.record(DiagnosticCode::RoomReconnecting, Some(number))
                .unwrap();
        }
        let files = fs::read_dir(log.directory()).unwrap().count();
        assert!(files <= ROTATED_FILES + 1);
        let recent = fs::read_to_string(log.directory().join("current.jsonl")).unwrap();
        assert!(
            recent
                .lines()
                .all(|line| serde_json::from_str::<serde_json::Value>(line).is_ok())
        );
        assert!(!recent.contains("Cookie"));
        assert!(!recent.contains("message"));
    }
}
